language: ruby
rvm:
- 2.3.3

script:
- "test ! \"$TRAVIS_EVENT_TYPE\" = \"cron\" || test $(curl -H \"Accept: application/vnd.github.v3+json\" https://api.github.com/repos/OctoPrint/plugins.octoprint.org/commits/gh-pages | grep -m1 sha | grep -Po 'sha\": \"[^\"]*' | cut -c 8-) = $(curl https://plugins.octoprint.org/ | grep build-revision | grep -Po 'content=\"[^\"]*' | cut -c 10-)"
- bundle exec jekyll build
- bundle exec jsonlint ./_site/plugins.json
- bundle exec jsonlint ./_site/search.json
- bundle exec jsonlint ./_site/notices.json
- bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --url-ignore "/ifttt\.com\/polar3d/" --file-ignore "/\.\/_site\/search\/index\.html/","/\.\/_site\/by_(author|tag|date|name)\/index\.html/" --log-level ':debug'

branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES

exclude: [vendor]
sudo: false
