language: ruby
rvm:
- 2.1

script:
- bundle exec jekyll build
- bundle exec jsonlint ./_site/plugins.json
- bundle exec jsonlint ./_site/search.json

branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES
