name: Publish to Github Pages

on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - gh-pages

jobs:
  build-and-publish:
    name: Publish to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 🐍 Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: 🏗 Enrich metadata
        run: |
          pip install -r _build/requirements.txt
          python ./_build/populate_additional_metadata.py
        env:
          GITHUB_CREDENTIALS: ${{ secrets.metadata_credentials }}

      - name: 🔨 Build page
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          jekyll/builder:3.8.6 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

      #- name: 🕵️‍♂️ Validate page
      #  run: |
      #    docker run \
      #    -v ${{ github.workspace }}:/data \
      #    cytopia/jsonlint _site/plugins.json

      - name: 🚀 Deploy page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./_site
          enable_jekyll: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
   
      - name: 📧 Discord success notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.discord_webhook }}
        uses: Ilshidur/action-discord@master
        with:
          args: '☑️ Page build for plugins.octoprint.org was successful'   
   
      - name: 📧 Discord failure notification
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.discord_webhook }}
        uses: Ilshidur/action-discord@master
        with:
          args: '🚫 Page build for plugins.octoprint.org failed'
