name: Test and validate page build

on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages

jobs:
  test-build:
    name: Test and validate page build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 🔨 Build page
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          jekyll/builder:3.8.6 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

      - name: 🕵️‍♂️ Validate plugins.json
        run: |
          docker run \
          -v ${{ github.workspace }}:/json \
          peterdavehello/jsonlint jsonlint -q /json/_site/plugins.json

      - name: 🕵️‍♂️ Validate notices.json
        run: |
          docker run \
          -v ${{ github.workspace }}:/json \
          peterdavehello/jsonlint jsonlint -q /json/_site/notices.json

      - name: 🕵️‍♂️ Validate search.json
        run: |
          docker run \
          -v ${{ github.workspace }}:/json \
          peterdavehello/jsonlint jsonlint -q /json/_site/search.json
